rules:
  bugs:
    constant-condition:
      level: ignore
  style:
    todo-comment:
      level: ignore
    prefer-some-in-iteration:
      level: ignore
    default-over-else:
      level: ignore
    opa-fmt:
      level: ignore
  imports:
    unresolved-reference:
      level: ignore
  idiomatic:
    no-defined-entrypoint:
      level: ignore
    directory-package-mismatch:
      level: ignore
  testing:
    todo-test:
      level: ignore
