# This policy evaluates installed software packages.
# Do NOT edit this file.

package opa_tooling.inventory

import rego.v1

high_severities := {"high", "critical"}

# Collect names of installed packages that appear in the vulnerability database
# with a high or critical severity rating.
vulnerable_packages contains pkg.name if {
	pkg := input.installed[_]
	vuln := data.vuln_db[pkg.name]
	vuln.severity in high_severities
}

# True when every package listed in data.required_packages is installed.
all_required_present if {
	required := data.required_packages[_]
	installed_names := {p.name | p := input.installed[_]}
	every r in data.required_packages {
		r in installed_names
	}
}

# A system is compliant when it has no vulnerable packages and all required
# packages are installed.
compliant if {
	count(vulnerable_packages) == 0
	all_required_present
}
